const db=window.supabase.createClient('https://jvgqvtnqncelbhuordzy.supabase.co','sb_publishable_4PusmhJVMm0b3Bm-2Y-FPQ__tnZZzZO');
const allowed=new Set(['Hoffi','Kai','Marcel']);
const teamSelect=document.getElementById('teamSelect'),form=document.getElementById('cashForm'),entries=document.getElementById('entries'),status=document.getElementById('status');
let teamId=null;
const esc=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const euro=v=>Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const localDateString=()=>{const n=new Date(),y=n.getFullYear(),m=String(n.getMonth()+1).padStart(2,'0'),d=String(n.getDate()).padStart(2,'0');return `${y}-${m}-${d}`};
function msg(t,c=''){status.textContent=t;status.className=`status ${c}`.trim()}
async function loadTeams(){const r=await db.from('jugend_teams').select('id,name,season').order('name');if(r.error)throw r.error;const current=teamId?String(teamId):teamSelect.value;teamSelect.innerHTML='<option value="">Mannschaft auswählen…</option>'+(r.data||[]).map(x=>`<option value="${x.id}">${esc(x.name)}${x.season?' · '+esc(x.season):''}</option>`).join('');if(current)teamSelect.value=current}
async function load(){
  const q=teamId?db.from('jugend_cashbook').select('id,team_id,entry_date,description,amount,category,note').eq('team_id',teamId):db.from('jugend_cashbook').select('id,team_id,entry_date,description,amount,category,note');
  const r=await q.order('entry_date',{ascending:false}).order('id',{ascending:false});if(r.error)throw r.error;
  let income=0,expense=0;for(const x of r.data||[]){const a=Number(x.amount);if(a>=0)income+=a;else expense+=Math.abs(a)}
  document.getElementById('income').textContent=euro(income);document.getElementById('expense').textContent=euro(expense);document.getElementById('balance').textContent=euro(income-expense);document.getElementById('count').textContent=`${r.data?.length||0} Buchungen`;
  entries.innerHTML=r.data?.length?r.data.map(x=>{const a=Number(x.amount);return `<div class="list-item"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><strong>${esc(x.description)}</strong><div>${new Date(x.entry_date+'T00:00:00').toLocaleDateString('de-DE')} · <span>${a>=0?'+':'-'}${euro(Math.abs(a))}</span>${x.category?' · '+esc(x.category):''}</div>${x.note?`<small>${esc(x.note)}</small>`:''}</div><button type="button" class="secondary cash-delete" data-id="${x.id}" aria-label="Buchung löschen">🗑️</button></div></div>`}).join(''):'<div class="empty">Noch keine Buchungen vorhanden.</div>';
  entries.querySelectorAll('.cash-delete').forEach(btn=>btn.addEventListener('click',()=>removeEntry(btn.dataset.id)));
}
async function removeEntry(id){if(!confirm('Diese Buchung wirklich löschen?'))return;const r=await db.from('jugend_cashbook').delete().eq('id',id);if(r.error){msg('❌ '+r.error.message,'error');return}msg('✓ Buchung gelöscht.','ok');await load()}
teamSelect.addEventListener('change',async()=>{teamId=Number(teamSelect.value)||null;try{await load()}catch(e){msg('❌ '+e.message,'error')}});
form.addEventListener('submit',async e=>{e.preventDefault();const tid=Number(teamSelect.value),amountInput=document.getElementById('amount').value,description=document.getElementById('description').value.trim(),entryDate=document.getElementById('entryDate').value;let amount=Number(amountInput);if(!tid){msg('Bitte Mannschaft auswählen.','error');return}if(!amountInput||!Number.isFinite(amount)||amount<=0){msg('Bitte einen Betrag größer als 0 eingeben.','error');return}if(!description||!entryDate){msg('Bitte Beschreibung und Datum eintragen.','error');return}if(document.getElementById('type').value==='expense')amount=-amount;const row={team_id:tid,entry_date:entryDate,description,amount,category:document.getElementById('category').value.trim()||null,note:document.getElementById('note').value.trim()||null};const r=await db.from('jugend_cashbook').insert(row).select('id').single();if(r.error){msg('❌ '+r.error.message,'error');return}form.reset();document.getElementById('entryDate').value=localDateString();teamSelect.value=String(tid);teamId=tid;msg('✓ Buchung gespeichert.','ok');await load()});
(async()=>{const {data}=await db.auth.getSession();if(!data.session||!allowed.has(data.session.user.user_metadata?.display_name)){location.replace('login.html');return}document.getElementById('entryDate').value=localDateString();try{await loadTeams();await load()}catch(e){msg('❌ '+e.message,'error')}})();