const db=window.supabase.createClient('https://jvgqvtnqncelbhuordzy.supabase.co','sb_publishable_4PusmhJVMm0b3Bm-2Y-FPQ__tnZZzZO');
const allowed=new Set(['Hoffi','Kai','Marcel']);
const teamSelect=document.getElementById('teamSelect'),form=document.getElementById('runForm'),list=document.getElementById('runList'),summary=document.getElementById('summary'),status=document.getElementById('status'),playerSelect=document.getElementById('playerSelect'),ranking=document.getElementById('ranking');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function localDateString(){const now=new Date(),y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),d=String(now.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function msg(t,c=''){status.textContent=t;status.className=`status ${c}`.trim()}
function durationText(minutes){const m=Number(minutes),h=Math.floor(m/60),rest=m%60;return h?`${h} Std. ${String(rest).padStart(2,'0')} Min.`:`${m} Min.`}
async function loadTeams(){teamSelect.innerHTML='<option value="">Mannschaft wird geladen…</option>';teamSelect.disabled=true;const {data,error}=await db.from('jugend_teams').select('id,name,season').order('id');if(error){teamSelect.innerHTML='<option value="">Fehler beim Laden</option>';throw error}if(!data?.length){teamSelect.innerHTML='<option value="">Keine Mannschaften vorhanden</option>';return}teamSelect.innerHTML='<option value="">Mannschaft auswählen…</option>'+data.map(x=>`<option value="${x.id}">${esc(x.name)}${x.season?' · '+esc(x.season):''}</option>`).join('');teamSelect.disabled=false}
async function loadPlayers(teamId){playerSelect.disabled=true;if(!teamId){playerSelect.innerHTML='<option value="">Erst Mannschaft auswählen…</option>';return}playerSelect.innerHTML='<option value="">Spieler werden geladen…</option>';const {data,error}=await db.from('jugend_players').select('id,display_name').eq('team_id',Number(teamId)).eq('active',true).order('display_name');if(error){playerSelect.innerHTML='<option value="">Fehler beim Laden</option>';throw error}if(!data?.length){playerSelect.innerHTML='<option value="">Keine aktiven Spieler vorhanden</option>';return}playerSelect.innerHTML='<option value="">Spieler auswählen…</option>'+data.map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`).join('');playerSelect.disabled=false}
function playerNote(row,teamRows){if(!row.runs)return '⚪ Noch kein Lauf erfasst';const maxRuns=Math.max(...teamRows.map(x=>x.runs));const maxKm=Math.max(...teamRows.map(x=>x.km));const notes=[];if(row.runs===maxRuns)notes.push('🏃 meiste Läufe');if(row.km===maxKm)notes.push('📏 meiste Kilometer');if(notes.length)return notes.join(' · ');if(row.runs>=3)return '🔥 regelmäßig dabei';if(row.runs>=1)return '👍 Laufleistung erfasst';return '⚪ Noch kein Lauf erfasst'}
function rankingBlock(team,players,runs){const teamRuns=runs.filter(r=>r.team_id===team.id);const rows=players.filter(p=>p.team_id===team.id).map(p=>{const own=teamRuns.filter(r=>r.player_id===p.id);return {id:p.id,name:p.display_name,runs:own.length,km:own.reduce((s,x)=>s+Number(x.distance_km||0),0),minutes:own.reduce((s,x)=>s+Number(x.duration_minutes||0),0)}}).sort((a,b)=>b.km-a.km||b.runs-a.runs||a.name.localeCompare(b.name,'de'));
if(!rows.length)return '';
const maxRuns=Math.max(...rows.map(x=>x.runs)),maxKm=Math.max(...rows.map(x=>x.km));
const body=rows.map((x,i)=>{const rank=i+1;const note=playerNote(x,rows);return `<div class="run-rank-row${rank===1?' top':''}"><span class="run-rank-place">${rank===1?'🥇':rank===2?'🥈':rank===3?'🥉':rank+'.'}</span><div class="run-rank-player"><strong>${esc(x.name)}</strong><small>${esc(note)}</small></div><span class="run-rank-runs">${x.runs} Läufe</span><span class="run-rank-km">${x.km.toFixed(2).replace('.',',')} km</span></div>`}).join('');
return `<div class="run-ranking-team"><div class="run-ranking-head"><div><h3>${esc(team.name==='C- Jugend'?'C1- Jugend':team.name)}</h3><small>${esc(team.season||'')}</small></div><strong>${rows.filter(x=>x.runs>0).length}/${rows.length} mit Lauf</strong></div><div class="run-ranking-list">${body}</div><div class="run-ranking-best">🏆 <strong>Beste Laufleistung:</strong> ${esc(rows.find(x=>x.runs===maxRuns)?.name||'–')} mit ${maxRuns} Läufen · ${esc(rows.find(x=>x.km===maxKm)?.name||'–')} mit ${maxKm.toFixed(2).replace('.',',')} km</div></div>`}
async function loadRuns(){const {data:runs,error}=await db.from('jugend_preparation_runs').select('id,team_id,player_id,player_name,run_date,distance_km,duration_minutes,note').order('run_date',{ascending:false}).order('id',{ascending:false});if(error)throw error;const rows=runs||[];const [teamsRes,playersRes]=await Promise.all([db.from('jugend_teams').select('id,name,season').order('name'),db.from('jugend_players').select('id,team_id,display_name').eq('active',true).order('display_name')]);if(teamsRes.error)throw teamsRes.error;if(playersRes.error)throw playersRes.error;const teams=teamsRes.data||[],players=playersRes.data||[];const teamMap=new Map(teams.map(x=>[x.id,x.name])),playerMap=new Map(players.map(x=>[x.id,x.display_name]));const km=rows.reduce((s,x)=>s+Number(x.distance_km||0),0),minutes=rows.reduce((s,x)=>s+Number(x.duration_minutes||0),0);summary.textContent=rows.length?`${rows.length} Läufe · ${km.toFixed(2).replace('.',',')} km · ${durationText(minutes)} Gesamtzeit`:'Noch keine Läufe.';list.innerHTML=rows.length?rows.map(x=>`<div class="list-item"><strong>🏃 ${esc(playerMap.get(x.player_id)||x.player_name||'Spieler unbekannt')}</strong><div>${esc(teamMap.get(x.team_id)||'Mannschaft unbekannt')} · ${new Date(x.run_date+'T00:00:00').toLocaleDateString('de-DE')} · ${Number(x.distance_km).toFixed(2).replace('.',',')} km · ${durationText(x.duration_minutes)}</div>${x.note?`<small>${esc(x.note)}</small>`:''}</div>`).join(''):'<div class="empty">Noch keine Läufe erfasst.</div>';
const relevantTeams=teams.filter(t=>/c\s*-?\s*(1\s*)?jugend|c1|c2/i.test(t.name));const teamBlocks=relevantTeams.map(t=>rankingBlock(t,players,rows)).filter(Boolean);if(!teamBlocks.length){ranking.innerHTML='<div class="empty">Noch keine Läufe für C1 oder C2 erfasst.</div>';return}const all=players.map(p=>{const own=rows.filter(r=>r.player_id===p.id);return {name:p.display_name,teamId:p.team_id,runs:own.length,km:own.reduce((s,x)=>s+Number(x.distance_km||0),0)}}).filter(x=>relevantTeams.some(t=>t.id===x.teamId));const leaderRuns=[...all].sort((a,b)=>b.runs-a.runs||b.km-a.km)[0],leaderKm=[...all].sort((a,b)=>b.km-a.km||b.runs-a.runs)[0];ranking.innerHTML=`<div class="run-overall"><div><span class="label">GESAMTWERTUNG C1 + C2</span><h3>Aktuelle Spitzenreiter</h3></div><div class="run-overall-grid"><div><span>🏃 Meiste Läufe</span><strong>${esc(leaderRuns?.name||'–')}</strong><b>${leaderRuns?.runs||0} Läufe</b></div><div><span>📏 Meiste Kilometer</span><strong>${esc(leaderKm?.name||'–')}</strong><b>${leaderKm?.km.toFixed(2).replace('.',',')||'0,00'} km</b></div></div></div>${teamBlocks.join('')}`}
teamSelect.addEventListener('change',async()=>{try{await loadPlayers(teamSelect.value);msg('')}catch(e){msg('❌ Spieler konnten nicht geladen werden: '+e.message,'error')}});
form.addEventListener('submit',async e=>{e.preventDefault();const row={team_id:Number(teamSelect.value),player_id:Number(playerSelect.value),run_date:document.getElementById('runDate').value,distance_km:Number(String(document.getElementById('distance').value).replace(',','.')),duration_minutes:Number(document.getElementById('duration').value),note:document.getElementById('note').value.trim()||null};if(!row.team_id){msg('Bitte Mannschaft auswählen.','error');return}if(!row.player_id){msg('Bitte Spieler auswählen.','error');return}if(!row.run_date){msg('Bitte Datum eintragen.','error');return}if(!Number.isFinite(row.distance_km)||row.distance_km<=0||row.distance_km>999.99){msg('Bitte gültige Kilometer eintragen.','error');return}if(!Number.isInteger(row.duration_minutes)||row.duration_minutes<1||row.duration_minutes>999){msg('Bitte eine gültige Dauer in Minuten eintragen.','error');return}const {error}=await db.from('jugend_preparation_runs').insert(row);if(error){msg('❌ '+error.message,'error');return}form.reset();playerSelect.innerHTML='<option value="">Erst Mannschaft auswählen…</option>';playerSelect.disabled=true;document.getElementById('runDate').value=localDateString();msg('✓ Lauf gespeichert und Auswertung aktualisiert.','ok');try{await loadRuns()}catch(e){msg('✓ Lauf gespeichert, Auswertung konnte nicht neu geladen werden.','error')}});
(async()=>{const {data,error}=await db.auth.getSession();if(error||!data.session||!allowed.has(data.session.user.user_metadata?.display_name)){location.replace('login.html');return}document.getElementById('runDate').value=localDateString();playerSelect.disabled=true;try{await loadTeams()}catch(e){msg('❌ Mannschaften konnten nicht geladen werden: '+e.message,'error');return}try{await loadPlayers(teamSelect.value);await loadRuns()}catch(e){msg('❌ '+e.message,'error')}})();